### ISSUE TITLE
Questions on Expanding on Your DAO Template

### ISSUE THREAD

**Issue by codesport** [PatrickAlphaC/dao-template#1]
Hi @PatrickAlphaC 

Thank you for this helpful tutorial!

I'm trying to learn Solidity. So, these are just questions on how to build upon your template and not issues.

1. Is some sort of "gatekeeper" function needed  to only allow  **holders of the token to make proposals and to vote**?  Or is this built into ERC20Votes.sol?  My actual use-case is [draft-ERC721Votes.sol ](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/draft-ERC721Votes.sol).  

2. What would be the purpose of  [ADDRESS_ZERO](https://github.com/PatrickAlphaC/dao-template/search?q=ADDRESS_ZERO) in the config and setup files? Is this to save gas?  

    * I naively would have thought the address of the [GovernorContract](https://github.com/PatrickAlphaC/dao-template/blob/main/contracts/governance_standard/GovernorContract.sol), [TimeLock](https://github.com/PatrickAlphaC/dao-template/blob/main/contracts/governance_standard/TimeLock.sol), or even the [GovernanceToken](https://github.com/PatrickAlphaC/dao-template/blob/main/contracts/GovernanceToken.sol) itself would be best.

3. It's [mentioned](https://github.com/PatrickAlphaC/dao-template#usage) that TimeLock.sol handles all the money, ownerships, etc

    * **How would this apply to the following use-case?**  If you want (i) to charge for your token and (ii) store those received funds in your DAO's Treasury, wouldn't this all be inside your token minter contract, that is, [GovernanceToken.sol](https://github.com/PatrickAlphaC/dao-template/blob/main/contracts/GovernanceToken.sol) and not in [TimeLock.sol](https://github.com/PatrickAlphaC/dao-template/blob/main/contracts/governance_standard/TimeLock.sol)?

**Comment by codesport** [comment]
Thank @PatrickAlphaC 

Your Answers are very thorough and educational.

Just some clarifying followups.

So anyone can propose, but only token holders may vote.  So is it safe to assume the chain of imported contracts from GovernorContract.sol  and ERCXXVotes.sol   ensure that only valid token holders can  vote?

**Linking Contracts**

I noticed there was no special solidity code to somehow 'link" these 3 contracts.  So this linking is only handled within our deployment scripts?  However,  I do know OpenZeppelin's  [Ownable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol) and `onlyOwner` directive does allow an owner to be specified and customized. So the linkages are through the contract deployer or whoever is designated as the *Owner* using `Owner.sol`

**Treasury Wallet**
Is the "Treasury Wallet"  a typically a separate contract or do we typically leave the funds in the contract that mints the tokens?  I'm not quite sure what is a best practice.  

I guess no matter which contract serves as the Treasury Wallet,  some sort of payable and receiver functionality is needed in it's solidity code.


**Time Lock**
I think I may understand now.   It's best practice for only TimeLock.sol to deposit and withdraw funds from that Treasury wallet/contract. Being a DAO, this ensures that funds are only moved by the democratic consensus of the DAO

Do you recommend importing Ownable.sol into the TimeLock.sol?  Or only into GovernorToken.sol and GovernorContract.sol?

**Comment by PatrickAlphaC** [comment]
> So anyone can propose, but only token holders may vote. So is it safe to assume the chain of imported contracts from GovernorContract.sol and ERCXXVotes.sol ensure that only valid token holders can vote?

Yes.

> I noticed there was no special solidity code to somehow 'link" these 3 contracts.

There is:

This "links" the governance token of choice to the governor contract: 
https://github.com/PatrickAlphaC/dao-template/blob/cb7ad324aca422a0b66de41a048e405c3d360f27/contracts/governance_standard/GovernorContract.sol#L21

This "links" the governor contract to the timelock:
https://github.com/PatrickAlphaC/dao-template/blob/cb7ad324aca422a0b66de41a048e405c3d360f27/deploy/04-setup-governance-contracts.ts#L23

> Treasury Wallet
The treasury wallet can simply be the timelock contract.

> Do you recommend importing Ownable.sol into the TimeLock.sol? Or only into GovernorToken.sol and GovernorContract.sol?

Neither. All the permissions are handled inside the contracts imported already.

**Comment by codesport** [comment]
@PatrickAlphaC   Thank you again. 

It all makes a lot more sense now!
