### ISSUE TITLE
Error running yarn hardhat deploy

### ISSUE THREAD

**Issue by waner11** [PatrickAlphaC/dao-template#13]
When I finished the script 03-deploy-governor-contract and try to run the deploy command, it throws the error below, I have the exact same code shown in the YT tutorial. The first two contracts are deployed but the error comes in the third one, the GovernorContract.

`Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="Transaction reverted: trying to deploy a contract whose code is too large", method="estimateGas"`

![Screen Shot 2022-07-05 at 12 39 40 AM](https://user-images.githubusercontent.com/22116259/177250617-2962fdec-d84a-44fb-b5d1-10b0058d42b9.png)

**Comment by Izmanovich** [comment]
Hey mate!
I had the same problem and I was able to fix it by changing this in `hardhat.config.ts`:
Change this line : ` solidity: "0.8.8",` for:
```
  solidity: {
    version: "0.8.8",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
```

I hope it helps 🙂

**Comment by PatrickAlphaC** [comment]
Can you make a PR with this? 🙏

**Comment by Izmanovich** [comment]
@PatrickAlphaC I just realized this piece of code was already included by @zeuslawyer here: https://github.com/PatrickAlphaC/dao-template/commit/d2afeded2b4307caf543d26ae319a64b9c176b35#diff-57cf5378f8cab20b02b279097ba6fad08eb53f747d81770045dda9c5f95effe3

**Comment by PatrickAlphaC** [comment]
Oh nice!

**Comment by waner11** [comment]
> Hey mate! I had the same problem and I was able to fix it by changing this in `hardhat.config.ts`: Change this line : ` solidity: "0.8.8",` for:
> 
> ```
>   solidity: {
>     version: "0.8.8",
>     settings: {
>       optimizer: {
>         enabled: true,
>         runs: 200,
>       },
>     },
>   },
> ```
> 
> I hope it helps 🙂

Thanks a lot man, this worked for me!
