### ISSUE TITLE
Error: Unable to propose a new proposal with error TypeError: Cannot read properties of undefined (reading 'args')

### ISSUE THREAD

**Issue by duytonghai** [PatrickAlphaC/dao-template#16]
Hi @PatrickAlphaC,

I'm getting an issue is unable to propose a new proposal when running script `yarn hardhat run scripts/propose.ts` on local. The interest thing is the script works well last week. I've run the script on `Goerli` testnet and it also works well.

 The error I got on local environment:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/9330550/186327346-ce77357d-c9b0-46ab-b0c1-03e22a532e71.png">

As you can see, the `events` response empty and the proposal cannot be created successfully.

I've investigating and found some updated from libraries `hardhat` and `@nomiclabs/hardhat-ethers` to fix the issue related to function `getContractAt` https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-ethers%402.1.1.

Unfortunately, we're using the library `"@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@0.3.0-beta.12"` in `package.json` to wrapping `hardhat-ethers`. I've checked and seen the library is no longer to update and maintenance.  

Could you please help to review the issue and give us your advice?

Thank you!

**Comment by PatrickAlphaC** [comment]
Can you please
1. Copy-paste code instead of doing a screenshot? 
2. Try to minimize the issue you're running into? It looks like it could be not necessarily be related to this repo.
3. If you can minimize the issue, it might make sense to make it on stack exchange eth

**Comment by duytonghai** [comment]
Hi Patrick,

I found the issue come from my mistake when running scripts. The script will work well when running with command `npx hardhat run scripts/vote.ts --network localhost`.

However, when I try to run with command `npx hardhat run scripts/vote.ts --network hardhat` or `npx hardhat run scripts/vote.ts`. Then the issue occurs.

Looks like the script only works with `--network localhost` instead `hardhat` by default.
