### ISSUE TITLE
I am getting this error when i try to deploy code

### ISSUE THREAD

**Issue by abdul-maajid** [PatrickAlphaC/dao-template#2]
When i run **yarn hardhat deploy** It gives me this error
No need to generate any newer typings.
An unexpected error occurred:

```

Error: ERROR processing skip func of /dao-governance/deploy/04-setup-governance-contract.ts:
TSError: ⨯ Unable to compile TypeScript:
deploy/04-setup-governance-contract.ts:15:33 - error TS2551: Property 'getContract' does not exist on type 'typeof import("/dao-governance/node_modules/ethers/lib/ethers") & HardhatEthersHelpers'. Did you mean 'getContractAt'?

15   const timeLock = await ethers.getContract("TimeLock", deployer);
```

Can anyone help about this.

**Comment by IoanSolovastru** [comment]
Hi, you have to add the package:
With npm :` npm i -D @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers`
With yarn: `yarn add --dev @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers`

**Comment by abdul-maajid** [comment]
> Hi, you have to add the package: With npm :` npm i -D @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers` With yarn: `yarn add --dev @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers`

Thanks Solved!!!
