### ISSUE TITLE
Update of the TimeLockController openzeppelin contract

### ISSUE THREAD

**Issue by 0xYoyo** [PatrickAlphaC/dao-template#27]
The constructor for this has changed and should be renounced in the TimeLock.sol contract after they added the "admin" to the constructor instead of the previous versions of this contract that would assign this admin to the deployer automatically

Here's how the updated version should look like:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/governance/TimelockController.sol";

contract TimeLock is TimelockController {
    constructor(
        uint256 minDelay, 
        address[] memory proposers, 
        address[] memory executors, 
        address admin
    ) TimelockController(minDelay, proposers, executors, admin) {}
}
```

**Comment by 0xYoyo** [comment]
After review I realized this should also be update in the 02-deploy-time-lock file to take 4 arguments instead of 3(add deployer as an admin)

**Comment by PatrickAlphaC** [comment]
You're using a newer version of the contracts. If you want to update this repo with the newer version of the contracts, that would be great.

**Comment by r0ushann** [comment]
> After review I realized this should also be update in the 02-deploy-time-lock file to take 4 arguments instead of 3(add deployer as an admin)

please specify the line too!

**Comment by PatrickAlphaC** [comment]
Fixed
