### ISSUE TITLE
ENOENT: no such file or directory, open 'proposals.json'

### ISSUE THREAD

**Issue by polyansofine** [PatrickAlphaC/dao-template#3]
Thanks for your coding.
I have some issue.
![image](https://user-images.githubusercontent.com/93109473/161499283-303dd326-6fa1-4e3d-b96d-4a6b1ea8d009.png)
please help me.
regard.

**Comment by PatrickAlphaC** [comment]
Could you make a `proposals.json` file with `{}` inside it at the root revel of this project?

**Comment by polyansofine** [comment]
hello @PatrickAlphaC !
your article and repo helped me a lot
thank you
But I'm curious about the DAO frontend
could you push frontend brach in progress?
best regard

**Comment by PatrickAlphaC** [comment]
Thanks!

I probably won't make a frontend for some time here, sorry!

**Comment by polyansofine** [comment]
I really appriciate you.
I'm curious how to get the list of proposals from the contract and the list of votes following that proposal in frontend.
can you explain me something ?

**Comment by PatrickAlphaC** [comment]
There is a mapping that keeps track of them.

You could write a function to view them.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7392d8373873bed5da9ac9a97811d709f8c5ffbb/contracts/governance/Governor.sol#L47
