### ISSUE TITLE
Governance Execution Delay?

### ISSUE THREAD

**Issue by RitzyDevBox** [PatrickAlphaC/dao-template#37]
Is there a configuration for delay in exeuction?   I could of sworn there was a property to delay exeuction to assure members have enough time from when the vote passes to get out of the DAO if necessary.  Maybe I'm thinking of a different governor?

I see these variables in OZ Settings:

    /**
     * @notice module:user-config
     * @dev Delay, in number of block, between the proposal is created and the vote starts. This can be increassed to
     * leave time for users to buy voting power, or delegate it, before the voting of a proposal starts.
     */
    function votingDelay() public view virtual returns (uint256);

    /**
     * @notice module:user-config
     * @dev Delay, in number of blocks, between the vote start and vote ends.
     *
     * NOTE: The {votingDelay} can delay the start of the vote. This must be considered when setting the voting
     * duration compared to the voting delay.
     */
    function votingPeriod() public view virtual returns (uint256); 

Is there a variable for delayed execution?

**Comment by PatrickAlphaC** [comment]
That's in the `TimeLock` contract: https://github.com/PatrickAlphaC/dao-template/blob/main/contracts/governance_standard/TimeLock.sol
