### ISSUE TITLE
Error when running queue-and-execute.ts on Sepolia

### ISSUE THREAD

**Issue by reachsak** [PatrickAlphaC/dao-template#45]
I've got everything working perfectly on localhost. Sepolia testnet works fine for Propose, vote. But I got an error when trying to run the Queue and execute.ts script. I saw the comment on the code ("this will fail on a testnet because you need to wait for the MIN_DELAY!") . But I'd like to know how can I change the code so that It'll run on testnet. 
Thanks

**Comment by PatrickAlphaC** [comment]
You'd have to just make the `MIN_DELAY` much lower than what it currently is!
