### ISSUE TITLE
A noob question, How does the contract ensure that the execution parameters are the same as those for proposal？

### ISSUE THREAD

**Issue by vegetax** [PatrickAlphaC/dao-template#7]
When a proposal is successful, is there any possibility for someone to change the parameters to execute?

**Comment by PatrickAlphaC** [comment]
Good question - when you go to "execute" only the ones that have passed the queue can be executed. 

```
  const executeTx = await governor.execute(
    [box.address],
    [0],
    [encodedFunctionCall],
    descriptionHash
  )
```

This will only pass if it has already been queued and passed.
